#!/usr/bin/env bash

[[local|localrc]]

# Load the default configuration options for midostack
DATABASE_PASSWORD=${DATABASE_PASSWORD:-$MIDOSTACK_PASSWORD}
RABBIT_PASSWORD=${RABBIT_PASSWORD:-$MIDOSTACK_PASSWORD}
SERVICE_TOKEN=${SERVICE_TOKEN:-$MIDOSTACK_PASSWORD}
SERVICE_PASSWORD=${SERVICE_PASSWORD:-$MIDOSTACK_PASSWORD}
ADMIN_PASSWORD=${ADMIN_PASSWORD:-$MIDOSTACK_PASSWORD}

USE_MIDONET=${USE_MIDONET:-true}

NOVA_USE_QUANTUM_API=v2
NOVA_USE_NEUTRON_API=v2

# Use UUID token, otherwise MN API would vomit with 500
KEYSTONE_TOKEN_FORMAT=UUID

# Need override here because we use it in 'midonet_stack' script
SCREEN_NAME=stack

# services
disable_service n-net
enable_service q-svc
enable_service q-dhcp
enable_service q-meta
#enable_service q-lbaas

if [ $USE_MIDONET = false ]; then
    enable_service q-agt
    enable_service q-l3
else
    Q_PLUGIN=midonet
    Q_L3_ENABLED=True
    Q_L3_ROUTER_PER_TENANT=True
    enable_service midonet
fi

# Disable Heat in thirdparty CI
if [ "$MIDONET_IN_THIRDPARTY_CI" = "True" ] ; then
    disable_service h-eng
    disable_service h-api
    disable_service h-api-cfn
    disable_service h-api-cw
fi

[[post-config|$NOVA_CONF]]
[DEFAULT]
libvirt_type=qemu
security_group_api=neutron
firewall_driver=nova.virt.firewall.NoopFirewallDriver

[MIDONET]
midonet_uri = http://$HOST_IP:$MIDONET_API_PORT/midonet-api
username = admin
password = $ADMIN_PASSWORD
project_id = admin
auth_url = http://$KEYSTONE_AUTH_HOST:35357/v2.0
midonet_use_tunctl = True

[[post-config|$NEUTRON_CONF]]
[quotas]
default_quota = -1
quota_network = -1
quota_subnet = -1
quota_port = -1
quota_security_group = -1

[[post-config|$LBAAS_AGENT_CONF_FILENAME]]
[DEFAULT]
interface_driver = neutron.agent.linux.interface.MidonetInterfaceDriver

[MIDONET]
midonet_uri = $MIDONET_API_URI
username = $MIDONET_USERNAME
password = $MIDONET_PASSWORD
project_id = $MIDONET_PROJECT_ID

[[post-config|$Q_DHCP_CONF_FILE]]
[DEFAULT]
interface_driver = neutron.agent.linux.interface.MidonetInterfaceDriver

[MIDONET]
midonet_uri = $MIDONET_API_URI
username = $MIDONET_USERNAME
password = $MIDONET_PASSWORD
project_id = $MIDONET_PROJECT_ID
