#!/usr/bin/env bash

# Load the default configuration options for midostack
MIDOSTACK_PASSWORD=${MIDOSTACK_PASSWORD:-gogomid0}
DATABASE_PASSWORD=${DATABASE_PASSWORD:-$MIDOSTACK_PASSWORD}
RABBIT_PASSWORD=${RABBIT_PASSWORD:-$MIDOSTACK_PASSWORD}
SERVICE_TOKEN=${SERVICE_TOKEN:-$MIDOSTACK_PASSWORD}
SERVICE_PASSWORD=${SERVICE_PASSWORD:-$MIDOSTACK_PASSWORD}
ADMIN_PASSWORD=${ADMIN_PASSWORD:-$MIDOSTACK_PASSWORD}

USE_MIDONET=${USE_MIDONET:-true}

NOVA_USE_QUANTUM_API=v2
NOVA_USE_NEUTRON_API=v2

KEYSTONE_TOKEN_FORMAT=UUID

# Need override here because we use it in 'midonet_stack' script
SCREEN_NAME=stack

# services
disable_service n-net
enable_service q-svc
enable_service q-dhcp
enable_service q-meta

if [ $USE_MIDONET = false ]; then
    enable_service q-agt
    enable_service q-l3
    enable_service q-lbaas
else
    Q_PLUGIN=midonet
    enable_service midonet
fi
