#!/usr/bin/env bash
# functions - Common functions used by MidoStack components

function is_devstack_cloned() {
    MIDO_DIR=$(pwd)
    DEVSTACK_DIR="$MIDO_DIR/devstack"
    if [ ! "$(ls -A $DEVSTACK_DIR)" ]; then
        echo "$DEVSTACK_DIR is empty. "
        echo "You problably haven't cloned devstack yet. "
        echo "Execute 'git submodule update --init' to clone devstack and run this script again"
        exit 1;
    fi
}
